"""fixing dealstatus

Revision ID: 6a360fdef84b
Revises: 603c4adbcdfe
Create Date: 2026-06-23 20:33:27.606355

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6a360fdef84b'
down_revision: Union[str, Sequence[str], None] = '603c4adbcdfe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TYPE dealstatus ADD VALUE 'canceled'")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
