"""Add phone number in users. Correct users

Revision ID: da49838a6e04
Revises: 2ac535b38a4f
Create Date: 2026-06-06 17:50:31.461456

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'da49838a6e04'
down_revision: Union[str, Sequence[str], None] = '2ac535b38a4f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clients', sa.Column('phone_number', sa.String(length=20), nullable=False))
    op.drop_column('users', 'name')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('name', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.drop_column('clients', 'phone_number')
    # ### end Alembic commands ###
